/* Browser-extracted source design; editable copy/assets live beside this component. */
import Link from "next/link";
import content from "./ValuesSection.content.json";
import assets from "./ValuesSection.assets.json";
import "./ValuesSection.css";

export function ValuesSection() {
  return (<>
    <section className="Values_values__FfIyQ"><div className="Values_values__content__UWxS4"><h2 className="Values_values__title__Uu33x">{content.text_001}</h2><p className="Text_text--display-m__q0ZjI Text_text--weight-bold__jl20H Values_values__description__m8_6h"><span className="">{content.text_002}</span></p><p className="Text_text--headline-m--extra-height__cgsfA Text_text--weight-regular__s9xkg Values_values__body-text-1__6MN1w"><span className="">{content.text_003}</span></p><p className="Text_text--body-l__nT4jd Text_text--weight-regular__s9xkg Values_values__body-text-2__Axb1B"><span className="">{content.text_004}</span></p><div className="DnaSpiral_dna-spiral__LgdVi"><div className="DnaSpiral_texts__6qCMb DnaSpiral_texts--left-group__Y2vr_"><span>{content.text_005}</span><span>{content.text_006}</span><span>{content.text_007}</span></div><div className="DnaSpiral_image__DvbKi"><span className="capture-04520533a0"><span className="capture-a6a8becacd"></span><img alt="" src={assets.image_001} decoding="async" sizes="100vw" className="capture-8cee0fc77c" /></span></div><div className="DnaSpiral_texts__6qCMb DnaSpiral_texts--right-group__eKHap"><span>{content.text_008}</span><span>{content.text_009}</span><span>{content.text_010}</span></div><div className="BlurredBubbles_bubble__OwYgZ BlurredBubbles_bubble--small__0Tsfk"><span className="capture-04520533a0"><span className="capture-ad158636f8"></span><img alt="" src={assets.image_002} decoding="async" sizes="100vw" className="capture-b210e675cd" /></span></div><div className="BlurredBubbles_bubble__OwYgZ BlurredBubbles_bubble--medium__A_5G2"><span className="capture-04520533a0"><span className="capture-ad158636f8"></span><img src={assets.image_003} decoding="async" sizes="100vw" className="capture-b210e675cd" alt="" /></span></div><div className="BlurredBubbles_bubble__OwYgZ BlurredBubbles_bubble--large__Gqd2h"><span className="capture-04520533a0"><span className="capture-ad158636f8"></span><img alt="" src={assets.image_004} decoding="async" sizes="100vw" className="capture-b210e675cd" /></span></div></div><div className="CareersLink_link__z84X9"><Link href="/contact" className="Button_button__30ukX Button_button--variant-filled-dark__wXoAl Button_button--radius-large__M_ook"><div className="Button_button__children__eLy5L">{content.text_011}</div><div className="Button_button__spinner__HYDVQ"><span></span><span></span><span></span></div></Link></div></div></section>
  </>);
}
